version: '3.8'

services:
  olmocr:
    build:
      context: .
      dockerfile: Dockerfile.new
      cache_from:
        - nvidia/cuda:12.9.0-devel-ubuntu24.04
    container_name: olmocr
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "30024:30024"
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ./localworkspace:/app/localworkspace
      - docker-cache:/var/lib/docker
    environment:
      - NVIDIA_VISIBLE_DEVICES=1  # Use the A6000 GPU
      - CUDA_VISIBLE_DEVICES=1
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_HOME=/usr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']  # Use GPU 1 (A6000)
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  docker-cache:
